### ISSUE TITLE
opticalrs==1.0.0

### ISSUE THREAD

**Issue by franfurey** [jkibele/OpticalRS#14]
Hi! we are using your library to try predicting seagrass. I believe in the requirements.txt this line its wrong:

opticalrs==1.0.0

You list as a dependency, when in fact that is the version of the package itself that is being installed. 

 Or im wrong? Let me know! Thanks for your public work!

**Comment by jkibele** [comment]
I'm glad to hear you're getting some use from OpticalRS. I think you're right, so I removed the `opticalrs` line from both the requirements.txt and the conda_requirements.txt files. Hopefully that'll help.

I work in a different field now (remote sensing of methane leaks), so there's not much time available to work on OpticalRS let alone documentation and testing. So this I haven't tested this change at all. Good luck!

**Comment by franfurey** [comment]
Np, thanks a lot for the response! Lets see if your repo help our models! Will let you know!
