### ISSUE TITLE
Command "python setup.py egg_info" failed with error code 1 in

### ISSUE THREAD

**Issue by dpoursanidis** [jkibele/OpticalRS#5]
Hi 

New in Python, i have install Anaconda 2.7 64bit.
Open the shell and pip install OpticalRS

(C:\Users\Dimitris\Anaconda2) C:\Users\Dimitris>pip install OpticalRS
Collecting OpticalRS
  Using cached OpticalRS-1.0.2.tar.gz
Requirement already satisfied: numpy in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Requirement already satisfied: pandas in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Requirement already satisfied: statsmodels in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Requirement already satisfied: matplotlib in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Requirement already satisfied: scikit-image in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Requirement already satisfied: scikit-learn in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Collecting GDAL (from OpticalRS)
  Using cached GDAL-2.2.3.tar.gz
Collecting geopandas (from OpticalRS)
  Using cached geopandas-0.3.0-py2.py3-none-any.whl
Collecting rasterstats (from OpticalRS)
  Using cached rasterstats-0.12.0-py2.py3-none-any.whl
Requirement already satisfied: scipy in c:\users\dimitris\anaconda2\lib\site-packages (from OpticalRS)
Requirement already satisfied: python-dateutil in c:\users\dimitris\anaconda2\lib\site-packages (from pandas->OpticalRS)
Requirement already satisfied: pytz>=2011k in c:\users\dimitris\anaconda2\lib\site-packages (from pandas->OpticalRS)
Requirement already satisfied: six>=1.10 in c:\users\dimitris\anaconda2\lib\site-packages (from matplotlib->OpticalRS)
Requirement already satisfied: backports.functools_lru_cache in c:\users\dimitris\anaconda2\lib\site-packages (from matplotlib->OpticalRS)
Requirement already satisfied: cycler>=0.10 in c:\users\dimitris\anaconda2\lib\site-packages (from matplotlib->OpticalRS)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in c:\users\dimitris\anaconda2\lib\site-packages (from matplotlib->OpticalRS)
Requirement already satisfied: networkx>=1.8 in c:\users\dimitris\anaconda2\lib\site-packages (from scikit-image->OpticalRS)
Requirement already satisfied: pillow>=2.1.0 in c:\users\dimitris\anaconda2\lib\site-packages (from scikit-image->OpticalRS)
Requirement already satisfied: PyWavelets>=0.4.0 in c:\users\dimitris\anaconda2\lib\site-packages (from scikit-image->OpticalRS)
Collecting descartes (from geopandas->OpticalRS)
  Using cached descartes-1.1.0-py2-none-any.whl
Collecting pyproj (from geopandas->OpticalRS)
  Using cached pyproj-1.9.5.1.tar.gz
Collecting fiona (from geopandas->OpticalRS)
  Using cached Fiona-1.7.11.tar.gz
Collecting shapely (from geopandas->OpticalRS)
  Using cached Shapely-1.6.4.post1.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "c:\users\dimitris\appdata\local\temp\pip-build-iybsdk\shapely\setup.py", line 80, in <module>
        from shapely._buildcfg import geos_version_string, geos_version, \
      File "shapely\_buildcfg.py", line 200, in <module>
        lgeos = CDLL("geos_c.dll")
      File "C:\Users\Dimitris\Anaconda2\lib\ctypes\__init__.py", line 366, in __init__
        self._handle = _dlopen(self._name, mode)
    WindowsError: [Error 126] The specified module could not be found

Any idea on what cause this error ?

I have update the "pip install --upgrade setuptools"

D.

**Comment by jkibele** [comment]
Hi Dimitris,

It looks like there was a problem trying to install one of the packages that OpticalRS depends on. It looks like Shapely was the problem. Try to get Shapely installed and working, then try installing OpticalRS again. You can find instructions on installing Shapely [here](https://github.com/Toblerity/Shapely).

Specifically, Shapely depends on Geos, and it looks like there may be a missing Geos .dll file. Good luck.

**Comment by dpoursanidis** [comment]
Hi,

Solve it by updating all anaconda packages using conda :)
Also, ru available for a cross comparison of SDB using Sentinel 2 data from Greece ?

D.

**Comment by jkibele** [comment]
I'm limited on the amount of time I can dedicate to it, but yeah, I'd love to help out. Message me on ResearchGate, and we can discuss it further.
